# Eğitim amaçlı Secret. stringData kullanmak base64 hesaplamak zorunda
# bırakmadığı için tercih edildi. Üretimde Sealed Secrets / External Secrets
# / Vault gibi bir çözüm kullanın.
apiVersion: v1
kind: Secret
metadata:
  name: k8sp-secret
  namespace: k8s-playground
type: Opaque
stringData:
  # envFrom ile env değişkeni olarak enjekte edilecekler
  DB_PASSWORD: "S3cret!Passw0rd"
  API_TOKEN: "t0k-1234567890-abcdef"

  # Volume olarak mount edildiğinde dosya gibi okunacaklar
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    EGITIM-ICIN-SAHTE-ANAHTAR
    -----END PRIVATE KEY-----
