# Uygulamanın ServiceAccount'u — Pod sayfasında "Service Account" kolonu için.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sp-sa
  namespace: k8s-playground
automountServiceAccountToken: true
